### PR TITLE
Bug/issue 22 alternative solution

### PR DESCRIPTION
**Pull request by kaelte**
issue #22 fixed

### CODE REVIEW

**Comment by kaelte** [comment]
Lokal laufen die Unit Tests durch: IntelliJ & Terminal (`mvn -T 2.0C -U clean instal`)
Hier schlägt Test `udf_durationInMillis` fehl :(

**Comment by kaelte** [comment]
The test case fail because the build server of github does not consider day light saving time whereas on my local machine the change is considered:

#### considering day light saving time
`durationInMillis(2019-10-27 02:00:00,2019-10-27 1:59:59.999) = 3600002`

#### without day light saving time
`durationInMillis(2019-10-27 02:00:00,2019-10-27 1:59:59.999) = 2`

The function uses the method [java.sql.Timestamp.getTime](https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html#getTime--) of which the result depends on the host environment of the Java Virtual Machine.

**Comment by kaelte** [comment]
test case `udf_durationInMillis` considers now dst offset of host system and thus succeeds.
@zkull , @pgruetter , @zzeekk you may want to approve this pull request  :smirk:

**Review by zzeekk — APPROVED** [review]
Very nice!

**Comment by kaelte** [comment]
@zzeekk, thanks for the clean up!

**Pull request merged**
